@name = testUser

### Create a new user
POST http://localhost:5000/users/
Content-Type: application/x-www-form-urlencoded

name={{name}}

### Get a user by name
GET http://localhost:5000/users/{{name}}

### Update user's best score
PUT http://localhost:5000/users/{{name}}
Content-Type: application/x-www-form-urlencoded

bestScore=1