@googleToken = xxxx
@accessToken = xxxx

### Authenticate user with token in headers
GET http://localhost:5000/user/auth/google/
access_token: {{googleToken}}

### Update user best score with token in Authorization header
PUT http://localhost:5000/user/score/
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "bestScore": 4
}
